### PR TITLE
feat: ignore any extension

### PR DESCRIPTION
**Pull request by pfdgithub**
like https://github.com/justkey007/tsc-alias/pull/123 but i want to import a json or any other file.

### CODE REVIEW

**Comment by raouldeheer** [comment]
@pfdgithub @justkey007 wouldn't it be a better idea to add this something like this as an optional replacer for compatibility?

**Comment by justkey007** [comment]
@raouldeheer  Yes I think it's better. Already tests have failed on this pull request.

**Comment by pfdgithub** [comment]
On an Apple M1, it is not possible to run test cases from the master branch.
The console doesn't output any progress and spawns a very large number of child processes.

```
Apple M1
macOS Big Sur 11.3.1
node.js 14.18.1
npm 6.14.15
pnpm 7.2.1
```

image
image

**Comment by justkey007** [comment]
@raouldeheer 
After careful consideration it is better to add the .json extension in the default replacer because a file with the .json extension is considered by nodejs as a module as much as a file with the .js extension.

**Comment by raouldeheer** [comment]
For `.json` and `.js` it makes sense but for extensions like `.less` a new replacer would be better.

**Comment by justkey007** [comment]
> For `.json` and `.js` it makes sense but for extensions like `.less` a new replacer would be better.

Yes on that I agree with you.

**Pull request merged**
