### PR TITLE
Fixed file extension undefined

### PR DESCRIPTION
**Pull request by raouldeheer**
This pr fixes the issue of the cli input overwriting the config input with undefined

### CODE REVIEW

**Comment by DerHannes85** [comment]
@raouldeheer / @justkey007 This change did not make it in the last release, was this intended? 

[compare/v1.8.0...v1.8.1](https://github.com/justkey007/tsc-alias/compare/v1.8.0...v1.8.1)

**Comment by raouldeheer** [comment]
The change seems to be included in the release on [unpkg](https://unpkg.com/browse/tsc-alias@1.8.1/dist/helpers/config.js) on line 100

**Comment by justkey007** [comment]
You're right @DerHannes85, it was during formatting that I made this mistake by overwriting the contents of the config.ts file when my code editor asked me to because the file was being modified. I will correct that now.

**Comment by justkey007** [comment]
You're right @DerHannes85, it was during formatting that I made this mistake by overwriting the contents of the config.ts file when my code editor asked me to because the file was being modified. I will correct that now.

**Pull request merged**
