### PR TITLE
Implemented asynchronous File IO

### LINKED ISSUE #30: Very slow build times?
I don't know if it's a problem you are able to solve, but tsc-alias is really screwing up my build times. I run tsc-alias both manually and in watch mode and it takes up about 90% of the build time. It would be really nice if some performance patches would be done, as I think it would boost this package popularity.

### PR DESCRIPTION
**Pull request by raouldeheer**
fixes #30 

- Added small performance test.
- Implemented asynchronous File IO.
- Tested globbyStream but compile time doubled (In project13, globbyStream: 36ms, this solution: 17ms, measured from start glob scan to finish replaceCount)

### CODE REVIEW

**Comment by jjangga0214** [comment]
@raouldeheer @justkey007 
I haven't tested, but if there are a lot of source files, MAYBE `globbyStream` becomes beneficial.

The experiment whose compile time was doubled from 17ms to 36ms is, IMHO, too weak evidence to assert synchronous glob pattern matching is actually better than async one. The additional 19ms might be just caused by a minor overhead which would not increase even if the number of source files increases.

**Comment by justkey007** [comment]
@jjangga0214 
What you are saying is possible and as soon as I have some time for the code I will do some tests in this direction in order to confirm this. Thank you

**Comment by raouldeheer** [comment]
@jjangga0214 @justkey007 

I've tested with over 100 source files.
These are the results:
| SourceFiles | GlobbyStream (ms) | GlobbySync (ms) |
|--------------|----------------------|--------------------|
| 100             | 138                          | 63                        |
| 500             | 569                          | 225                      |
| 7000           | 7333                        | 2585                    |

When testing with 10000 files, ran into nodejs open file limit at 8360.
Tested using [this](https://github.com/raouldeheer/tsc-alias/tree/7000-src-file-test) branch.

As seen in the results GlobbyStream takes twice as much time as the GlobbySync method

**Comment by justkey007** [comment]
Thank you very much @raouldeheer for the tests carried out, it really proves that the GlobbySync is the best.

**Pull request merged**
